spring.application.name=aicreator

scheduler.interval.ms=1800000
agent.max.posts.per.day=8

gemini.api.key=${GEMINI_API_KEY}
news.api.key=${NEWS_API_KEY}

upstash.redis.url=${UPSTASH_REDIS_REST_URL}
upstash.redis.token=${UPSTASH_REDIS_REST_TOKEN}